runtime: python39
instance_class: F1
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  max_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 10

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
